class_name MainMenu
extends Control


@onready var start_button: Button = $MarginContainer/VBoxContainer/HBoxContainer/VBoxContainer/Button
@onready var settings_button: Button = $MarginContainer/VBoxContainer/HBoxContainer/VBoxContainer/Button2
@onready var exit_button: Button = $MarginContainer/VBoxContainer/HBoxContainer/VBoxContainer/Button3
@onready var start_level = preload("res://Main_menu/main_menu.tscn") as PackedScene

func _ready():
	start_button.button_down.connect(on_start_pressed)
	settings_button.button_down.connect(on_settings_pressed)
	exit_button.button_down.connect(on_exit_pressed)

func on_start_pressed()-> void:
	print("scene changed!")
	get_tree().change_scene_to_packed(start_level)

func on_settings_pressed()->void:
	pass

func on_exit_pressed() ->void:
	get_tree().quit()
